
  CREATE OR REPLACE FORCE VIEW "V_ANTIGUEDADES" ("CVE_GPO_EMPRESA", "CVE_EMPRESA", "ID_PRESTAMO", "CVE_PRESTAMO", "APLICA_A", "CVE_NOMBRE", "NOMBRE", "NUM_INTEGRANTES", "ID_SUCURSAL", "NOM_SUCURSAL", "ID_REGIONAL", "NOM_REGIONAL", "CVE_ASESOR_CREDITO", "ID_PERSONA", "NOM_COMPLETO_ASESOR", "ID_ETAPA_PRESTAMO", "MONTO_AUTORIZADO", "CARGO_INICIAL", "NUM_DIAS_ATRASO_ACTUAL", "NUM_DIAS_ATRASO_MAX", "NUM_DIAS_ANTIGUEDAD", "CVE_CATEGORIA_ATRASO", "F_PROX_PAGO", "F_ULT_PAGO_REALIZADO", "F_ULT_AMORTIZACION", "VENCIDO_INTERES", "VENCIDO_CAPITAL", "VENCIDO_SEGURO", "VENCIDO_RECARGO", "SALDO_INTERES", "SALDO_CAPITAL", "SALDO_SEGURO", "SALDO_RECARGO", "CUOTA") AS 
  SELECT P.CVE_GPO_EMPRESA,
    P.CVE_EMPRESA,
    P.ID_PRESTAMO_GRUPO ID_PRESTAMO,
    P.CVE_PRESTAMO_GRUPO CVE_PRESTAMO,
    'GRUPO' APLICA_A,
    P.ID_GRUPO CVE_NOMBRE,
    N.NOM_GRUPO NOMBRE,
    N.NUM_INTEGRANTES,
    N.ID_SUCURSAL,
    S.NOM_SUCURSAL,
    S.ID_REGIONAL,
    R.NOM_REGIONAL,
    P.CVE_ASESOR_CREDITO,
    PA.ID_PERSONA,
    NA.NOM_COMPLETO,
    P.ID_ETAPA_PRESTAMO,
    A.MONTO_AUTORIZADO,
    B.CARGO_INICIAL,
    P.NUM_DIAS_ATRASO_ACTUAL,
    P.NUM_DIAS_ATRASO_MAX,
    P.NUM_DIAS_ANTIGUEDAD,
    P.CVE_CATEGORIA_ATRASO,
    P.F_PROX_PAGO,
    P.F_ULT_PAGO_REALIZADO,
    P.F_ULT_AMORTIZACION,
    AA.VENCIDO_INTERES,
    AB.IMP_DEBE_HOY VENCIDO_CAPITAL,
    AC.IMP_DEBE_HOY VENCIDO_SEGURO,
    AD.IMP_DEBE_HOY VENCIDO_RECARGO,
    AE.SALDO_INTERES,
    AF.IMP_SALDO_TOTAL SALDO_CAPITAL,
    AG.IMP_SALDO_TOTAL SALDO_SEGURO,
    AH.IMP_SALDO_TOTAL SALDO_RECARGO,
    AI.CUOTA
  FROM SIM_PRESTAMO_GRUPO P,
    SIM_GRUPO N,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO_GRUPO,
      SUM(MONTO_AUTORIZADO) MONTO_AUTORIZADO
    FROM SIM_PRESTAMO_GPO_DET
    GROUP BY ID_PRESTAMO_GRUPO,
      CVE_GPO_EMPRESA,
      CVE_EMPRESA
    ) A,
    (SELECT P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO_GRUPO,
      SUM(C.CARGO_INICIAL) CARGO_INICIAL
    FROM SIM_PRESTAMO_GPO_DET P,
      SIM_PRESTAMO_GPO_CARGO C
    WHERE C.CVE_GPO_EMPRESA   = P.CVE_GPO_EMPRESA
    AND C.CVE_EMPRESA         = P.CVE_EMPRESA
    AND C.ID_PRESTAMO_GRUPO   = P.ID_PRESTAMO_GRUPO
    AND C.ID_FORMA_APLICACION = 1
    GROUP BY P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO_GRUPO
    )B,
    SIM_CAT_SUCURSAL S,
    SIM_CAT_REGIONAL R,
    RS_GRAL_USUARIO PA,
    RS_GRAL_PERSONA NA,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) VENCIDO_INTERES
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Interés', 'Interés Extra', 'Iva De Intereses', 'Iva Interes Extra', 'Pago Interés', 'Pago Interés Extra', 'Pago Iva De Intereses', 'Pago Iva Interes Extra')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AA,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) IMP_DEBE_HOY
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Capital','Pago Capital')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AB,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) IMP_DEBE_HOY
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Seguro Deudor','Pago Seguro Deudor')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AC,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) IMP_DEBE_HOY
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Pago Tardío','Pago Pago Tardío')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AD,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) SALDO_INTERES
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Interés', 'Interés Extra', 'Iva De Intereses', 'Iva Interes Extra', 'Pago Interés', 'Pago Interés Extra', 'Pago Iva De Intereses', 'Pago Iva Interes Extra')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AE,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) IMP_SALDO_TOTAL
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Capital', 'Pago Capital')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AF,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) IMP_SALDO_TOTAL
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Seguro Deudor','Pago Seguro Deudor')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AG,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) IMP_SALDO_TOTAL
    FROM V_SIM_PRESTAMO_GPO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Pago Tardío','Pago Pago Tardío')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AH,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO_GRUPO,
      AVG(PAGO_TOTAL) CUOTA
    FROM V_TABLA_AMORTIZACION_GRUPAL
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO_GRUPO
    ORDER BY ID_PRESTAMO_GRUPO
    ) AI
  WHERE N.CVE_GPO_EMPRESA      = P.CVE_GPO_EMPRESA
  AND N.CVE_EMPRESA            = P.CVE_EMPRESA
  AND N.ID_GRUPO               = P.ID_GRUPO
  AND A.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA            = P.CVE_EMPRESA
  AND A.ID_PRESTAMO_GRUPO      = P.ID_PRESTAMO_GRUPO
  AND B.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND B.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND B.ID_PRESTAMO_GRUPO (+)  = P.ID_PRESTAMO_GRUPO
  AND S.CVE_GPO_EMPRESA        = N.CVE_GPO_EMPRESA
  AND S.CVE_EMPRESA            = N.CVE_EMPRESA
  AND S.ID_SUCURSAL            = N.ID_SUCURSAL
  AND R.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND R.CVE_EMPRESA            = P.CVE_EMPRESA
  AND R.ID_REGIONAL            = S.ID_REGIONAL
  AND P.CVE_GPO_EMPRESA        = PA.CVE_GPO_EMPRESA
  AND P.CVE_EMPRESA            = PA.CVE_EMPRESA
  AND P.CVE_ASESOR_CREDITO     = PA.CVE_USUARIO
  AND NA.CVE_GPO_EMPRESA       = PA.CVE_GPO_EMPRESA
  AND NA.CVE_EMPRESA           = PA.CVE_EMPRESA
  AND NA.ID_PERSONA            = PA.ID_PERSONA
  AND AA.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AA.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AA.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AB.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AB.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AB.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AC.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AC.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AC.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AD.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AD.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AD.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AE.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AE.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AE.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AF.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AF.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AF.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AG.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AG.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AG.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AH.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AH.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AH.ID_PRESTAMO (+)       = P.ID_PRESTAMO_GRUPO
  AND AI.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AI.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AI.ID_PRESTAMO_GRUPO (+) = P.ID_PRESTAMO_GRUPO
  AND P.ID_ETAPA_PRESTAMO      = 7
  UNION
  SELECT P.CVE_GPO_EMPRESA,
    P.CVE_EMPRESA,
    P.ID_PRESTAMO ID_PRESTAMO,
    P.CVE_PRESTAMO,
    'INDIVIDUAL' APLICA_A,
    P.ID_CLIENTE CVE_NOMBRE,
    N.NOM_COMPLETO NOMBRE,
    1 NUMERO,
    P.ID_SUCURSAL,
    S.NOM_SUCURSAL,
    S.ID_REGIONAL,
    R.NOM_REGIONAL,
    P.CVE_ASESOR_CREDITO,
    PA.ID_PERSONA,
    NA.NOM_COMPLETO,
    P.ID_ETAPA_PRESTAMO,
    M.MONTO_AUTORIZADO,
    NVL(C.CARGO_INICIAL,C.PORCENTAJE_MONTO/100*M.MONTO_AUTORIZADO) CARGO_INICIAL,
    P.NUM_DIAS_ATRASO_ACTUAL,
    P.NUM_DIAS_ATRASO_MAX,
    P.NUM_DIAS_ANTIGUEDAD,
    P.CVE_CATEGORIA_ATRASO,
    P.F_PROX_PAGO,
    P.F_ULT_PAGO_REALIZADO,
    P.F_ULT_AMORTIZACION,
    AA.VENCIDO_INTERES,
    AB.IMP_DEBE_HOY VENCIDO_CAPITAL,
    AC.IMP_DEBE_HOY VENCIDO_SEGURO,
    AD.IMP_DEBE_HOY VENCIDO_RECARGO,
    AE.SALDO_INTERES,
    AF.IMP_SALDO_TOTAL SALDO_CAPITAL,
    AG.IMP_SALDO_TOTAL SALDO_SEGURO,
    AH.IMP_SALDO_TOTAL SALDO_RECARGO,
    AI.CUOTA
  FROM SIM_PRESTAMO P,
    RS_GRAL_PERSONA N,
    SIM_CLIENTE_MONTO M,
    SIM_PRESTAMO_CARGO_COMISION C,
    SIM_CAT_SUCURSAL S,
    SIM_CAT_REGIONAL R,
    RS_GRAL_USUARIO PA,
    RS_GRAL_PERSONA NA,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) VENCIDO_INTERES
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Interés', 'Interés Extra', 'Iva De Intereses', 'Iva Interes Extra', 'Pago Interés', 'Pago Interés Extra', 'Pago Iva De Intereses', 'Pago Iva Interes Extra')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AA,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) IMP_DEBE_HOY
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Capital','Pago Capital')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AB,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) IMP_DEBE_HOY
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Seguro Deudor','Pago Seguro Deudor')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AC,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_DEBE_HOY) IMP_DEBE_HOY
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Pago Tardío','Pago Pago Tardío')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AD,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) SALDO_INTERES
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Interés', 'Interés Extra', 'Iva De Intereses', 'Iva Interes Extra', 'Pago Interés', 'Pago Interés Extra', 'Pago Iva De Intereses', 'Pago Iva Interes Extra')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AE,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) IMP_SALDO_TOTAL
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Capital','Pago Capital')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AF,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) IMP_SALDO_TOTAL
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Seguro Deudor','Pago Seguro Deudor')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AG,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      SUM(IMP_SALDO_TOTAL) IMP_SALDO_TOTAL
    FROM V_SIM_PRESTAMO_RES_EDO_CTA
    WHERE DESC_MOVIMIENTO IN ('Pago Tardío','Pago Pago Tardío')
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AH,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO,
      AVG(PAGO_TOTAL) CUOTA
    FROM V_TABLA_AMORT_INDIVIDUAL
    GROUP BY CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO
    ORDER BY ID_PRESTAMO
    ) AI
  WHERE P.ID_PRESTAMO NOT IN
    (SELECT ID_PRESTAMO FROM SIM_PRESTAMO_GPO_DET
    )
  AND N.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND N.CVE_EMPRESA            = P.CVE_EMPRESA
  AND N.ID_PERSONA             = P.ID_CLIENTE
  AND M.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND M.CVE_EMPRESA            = P.CVE_EMPRESA
  AND M.ID_PRESTAMO            = P.ID_PRESTAMO
  AND C.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND C.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND C.ID_PRESTAMO (+)        = P.ID_PRESTAMO
  AND C.ID_FORMA_APLICACION (+)= 1
  AND C.ID_CARGO_COMISION (+)  = 9
  AND S.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND S.CVE_EMPRESA            = P.CVE_EMPRESA
  AND S.ID_SUCURSAL            = P.ID_SUCURSAL
  AND R.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND R.CVE_EMPRESA            = P.CVE_EMPRESA
  AND R.ID_REGIONAL            = S.ID_REGIONAL
  AND P.CVE_GPO_EMPRESA        = PA.CVE_GPO_EMPRESA
  AND P.CVE_EMPRESA            = PA.CVE_EMPRESA
  AND P.CVE_ASESOR_CREDITO     = PA.CVE_USUARIO
  AND NA.CVE_GPO_EMPRESA       = PA.CVE_GPO_EMPRESA
  AND NA.CVE_EMPRESA           = PA.CVE_EMPRESA
  AND NA.ID_PERSONA            = PA.ID_PERSONA
  AND AA.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AA.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AA.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AB.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AB.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AB.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AC.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AC.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AC.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AD.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AD.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AD.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AE.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AE.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AE.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AF.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AF.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AF.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AG.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AG.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AG.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AH.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AH.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AH.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND AI.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND AI.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND AI.ID_PRESTAMO (+)       = P.ID_PRESTAMO
  AND P.ID_ETAPA_PRESTAMO      = 7;
 

