
  CREATE OR REPLACE FORCE VIEW "V_CREDITO" ("CVE_GPO_EMPRESA", "CVE_EMPRESA", "ID_PRESTAMO", "CVE_PRESTAMO", "APLICA_A", "CVE_NOMBRE", "NOMBRE", "ID_PRODUCTO", "NOM_PRODUCTO", "NUM_CICLO", "ID_PERIODICIDAD_PRODUCTO", "PERIODICIDAD_PRODUCTO", "PLAZO", "DIA_SEMANA_PAGO", "CVE_METODO", "NOM_METODO", "ID_PERIODICIDAD_TASA", "PERIODICIDAD_TASA", "VALOR_TASA", "ID_SUCURSAL", "NOM_SUCURSAL", "TASA_SUCURSAL", "DIRECCION_SUCURSAL", "CVE_USUARIO_COORDINADOR", "NOM_COORDINADOR_SUCURSAL", "ID_REGIONAL", "NOM_REGIONAL", "FECHA_ENTREGA", "FECHA_REAL", "FECHA_FIN", "CVE_ASESOR_CREDITO", "NOM_ASESOR_CREDITO", "CVE_ASESOR_FUNDADOR", "NOM_ASESOR_FUNDADOR", "ID_ETAPA_PRESTAMO", "MONTO_FIJO_PERIODO", "MONTO_AUTORIZADO", "CARGO_INICIAL", "NUM_LINEA", "CVE_FONDEADOR", "NOM_FONDEADOR") AS 
  SELECT P.CVE_GPO_EMPRESA,
    P.CVE_EMPRESA,
    P.ID_PRESTAMO ID_PRESTAMO,
    P.CVE_PRESTAMO,
    'INDIVIDUAL' APLICA_A,
    P.ID_CLIENTE CVE_NOMBRE,
    N.NOM_COMPLETO NOMBRE,
    P.ID_PRODUCTO,
    O.NOM_PRODUCTO,
    P.NUM_CICLO,
    P.ID_PERIODICIDAD_PRODUCTO,
    PE.NOM_PERIODICIDAD PERIODICIDAD_PRODUCTO,
    P.Plazo,
    P.DIA_SEMANA_PAGO,
    P.Cve_Metodo,
    ME.NOM_METODO,
    DECODE(P.ID_PERIODICIDAD_TASA,NULL,
    (SELECT ID_PERIODICIDAD
    FROM SIM_CAT_TASA_REFERENCIA
    WHERE ID_TASA_REFERENCIA =
      (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
      )
    ),P.ID_PERIODICIDAD_TASA) ID_PERIODICIDAD_TASA,
    PET.NOM_PERIODICIDAD PERIODICIDAD_TASA,
    DECODE(P.VALOR_TASA,NULL,
    (SELECT VALOR
    FROM SIM_CAT_TASA_REFER_DETALLE
    WHERE ID_TASA_REFERENCIA =
      (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
      )
    AND FECHA_PUBLICACION =
      (SELECT MAX(FECHA_PUBLICACION) FECHA_TASA_REFERENCIA
      FROM
        (SELECT FECHA_PUBLICACION
        FROM SIM_CAT_TASA_REFER_DETALLE
        WHERE ID_TASA_REFERENCIA =
          (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
          )
        AND FECHA_PUBLICACION < SYSDATE
        )
      )
    ),P.VALOR_TASA) VALOR_TASA,
    P.ID_SUCURSAL,
    S.NOM_SUCURSAL,
    S.TASA_IVA,
    D.CALLE
    ||' '
    ||D.NUMERO_INT
    ||' '
    ||D.NOM_ASENTAMIENTO
    ||' '
    ||D.NOM_DELEGACION
    ||' '
    ||D.NOM_ESTADO
    ||' '
    ||'C.P.'
    ||' '
    ||D.CODIGO_POSTAL DIRECCION_SUCURSAL,
    S.CVE_USUARIO_COORDINADOR,
    PCS.NOM_COMPLETO NOM_COORDINADOR_SUCURSAL,
    S.ID_REGIONAL,
    R.NOM_REGIONAL,
    P.FECHA_ENTREGA,
    P.FECHA_REAL,
    T.FECHA_FIN,
    P.CVE_ASESOR_CREDITO,
    PAA.NOM_COMPLETO NOM_ASESOR_CREDITO,
    P.CVE_ASESOR_FUNDADOR,
    PAF.NOM_COMPLETO NOM_ASESOR_FUNDADOR,
    P.ID_ETAPA_PRESTAMO,
    P.MONTO_FIJO_PERIODO,
    M.MONTO_AUTORIZADO,
    NVL(C.CARGO_INICIAL,C.PORCENTAJE_MONTO/100*M.MONTO_AUTORIZADO) CARGO_INICIAL,
    P.NUM_LINEA,
    L.CVE_FONDEADOR,
    F.NOM_FONDEADOR
  FROM SIM_PRESTAMO P,
    RS_GRAL_PERSONA N,
    SIM_CLIENTE_MONTO M,
    SIM_PRESTAMO_CARGO_COMISION C,
    Sim_Producto O,
    SIM_CAT_METODO ME,
    SIM_CAT_SUCURSAL S,
    RS_GRAL_DOMICILIO D,
    SIM_CAT_PERIODICIDAD PE,
    SIM_CAT_PERIODICIDAD PET,
    (SELECT P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO,
      MAX(T.FECHA_AMORTIZACION) FECHA_FIN
    FROM SIM_PRESTAMO P,
      SIM_TABLA_AMORTIZACION T
    WHERE T.CVE_GPO_EMPRESA = P.CVE_GPO_EMPRESA
    AND T.CVE_EMPRESA       = P.CVE_EMPRESA
    AND T.ID_PRESTAMO       = P.ID_PRESTAMO
    GROUP BY P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO
    )T,
    RS_GRAL_USUARIO UAF,
    RS_GRAL_PERSONA PAF,
    RS_GRAL_USUARIO UAA,
    RS_GRAL_PERSONA PAA,
    SIM_CAT_REGIONAL R,
    RS_GRAL_USUARIO UCS,
    RS_GRAL_PERSONA PCS,
    SIM_CAT_FONDEADOR_LINEA L,
    SIM_CAT_FONDEADOR F
  WHERE P.ID_PRESTAMO NOT IN
    (SELECT ID_PRESTAMO FROM SIM_PRESTAMO_GPO_DET
    )
  AND N.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND N.CVE_EMPRESA            = P.CVE_EMPRESA
  AND N.ID_PERSONA             = P.ID_CLIENTE
  AND M.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND M.CVE_EMPRESA            = P.CVE_EMPRESA
  AND M.ID_PRESTAMO            = P.ID_PRESTAMO
  AND C.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND C.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND C.ID_PRESTAMO (+)        = P.ID_PRESTAMO
  AND C.ID_FORMA_APLICACION (+)= 1
  AND C.ID_CARGO_COMISION (+)  = 9
  AND O.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND O.CVE_EMPRESA            = P.CVE_EMPRESA
  AND O.Id_Producto            = P.Id_Producto
  AND Me.Cve_Gpo_Empresa       = P.Cve_Gpo_Empresa
  AND Me.Cve_Empresa           = P.Cve_Empresa
  AND ME.CVE_METODO            = P.CVE_METODO
  AND S.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND S.CVE_EMPRESA            = P.CVE_EMPRESA
  AND S.ID_SUCURSAL            = P.ID_SUCURSAL
  AND D.CVE_GPO_EMPRESA (+)    = S.CVE_GPO_EMPRESA
  AND D.CVE_EMPRESA (+)        = S.CVE_EMPRESA
  AND D.ID_DOMICILIO (+)       = S.ID_DIRECCION
  AND PE.CVE_GPO_EMPRESA       = P.CVE_GPO_EMPRESA
  AND PE.CVE_EMPRESA           = P.CVE_EMPRESA
  AND PE.ID_PERIODICIDAD       = P.ID_PERIODICIDAD_PRODUCTO
  AND PET.CVE_GPO_EMPRESA      = P.CVE_GPO_EMPRESA
  AND PET.CVE_EMPRESA          = P.CVE_EMPRESA
  AND PET.ID_PERIODICIDAD      = P.ID_PERIODICIDAD_TASA
  AND T.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND T.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND T.ID_PRESTAMO (+)        = P.ID_PRESTAMO
  AND UAF.CVE_GPO_EMPRESA (+)  = P.CVE_GPO_EMPRESA
  AND UAF.CVE_EMPRESA (+)      = P.CVE_EMPRESA
  AND UAF.CVE_USUARIO (+)      = P.CVE_ASESOR_FUNDADOR
  AND PAF.CVE_GPO_EMPRESA (+)  = UAF.CVE_GPO_EMPRESA
  AND PAF.CVE_EMPRESA (+)      = UAF.CVE_EMPRESA
  AND PAF.ID_PERSONA (+)       = UAF.ID_PERSONA
  AND UAA.CVE_GPO_EMPRESA (+)  = P.CVE_GPO_EMPRESA
  AND UAA.CVE_EMPRESA (+)      = P.CVE_EMPRESA
  AND UAA.CVE_USUARIO (+)      = P.CVE_ASESOR_FUNDADOR
  AND PAA.CVE_GPO_EMPRESA (+)  = UAA.CVE_GPO_EMPRESA
  AND PAA.CVE_EMPRESA (+)      = UAA.CVE_EMPRESA
  AND PAA.ID_PERSONA (+)       = UAA.ID_PERSONA
  AND R.CVE_GPO_EMPRESA (+)    = S.CVE_GPO_EMPRESA
  AND R.CVE_EMPRESA (+)        = S.CVE_EMPRESA
  AND R.ID_REGIONAL (+)        = S.ID_REGIONAL
  AND UCS.CVE_GPO_EMPRESA (+)  = S.CVE_GPO_EMPRESA
  AND UCS.CVE_EMPRESA (+)      = S.CVE_EMPRESA
  AND UCS.CVE_USUARIO (+)      = S.CVE_USUARIO_COORDINADOR
  AND PCS.CVE_GPO_EMPRESA (+)  = UCS.CVE_GPO_EMPRESA
  AND PCS.CVE_EMPRESA (+)      = UCS.CVE_EMPRESA
  AND PCS.ID_PERSONA (+)       = UCS.ID_PERSONA
  AND L.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND L.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND L.NUM_LINEA (+)          = P.NUM_LINEA
  AND F.CVE_GPO_EMPRESA (+)    = L.CVE_GPO_EMPRESA
  AND F.CVE_EMPRESA (+)        = L.CVE_EMPRESA
  AND F.CVE_FONDEADOR (+)      = L.CVE_FONDEADOR
  UNION
  SELECT P.CVE_GPO_EMPRESA,
    P.CVE_EMPRESA,
    P.ID_PRESTAMO_GRUPO ID_PRESTAMO,
    P.CVE_PRESTAMO_GRUPO CVE_PRESTAMO,
    'GRUPO' APLICA_A,
    P.ID_GRUPO CVE_NOMBRE,
    N.NOM_GRUPO NOMBRE,
    P.ID_PRODUCTO,
    O.NOM_PRODUCTO,
    P.NUM_CICLO,
    P.ID_PERIODICIDAD_PRODUCTO,
    PE.NOM_PERIODICIDAD PERIODICIDAD_PRODUCTO,
    P.Plazo,
    P.DIA_SEMANA_PAGO,
    P.Cve_Metodo,
    ME.NOM_METODO,
    DECODE(P.ID_PERIODICIDAD_TASA,NULL,
    (SELECT ID_PERIODICIDAD
    FROM SIM_CAT_TASA_REFERENCIA
    WHERE ID_TASA_REFERENCIA =
      (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
      )
    ),P.ID_PERIODICIDAD_TASA) ID_PERIODICIDAD_TASA,
    PET.NOM_PERIODICIDAD PERIODICIDAD_TASA,
    DECODE(P.VALOR_TASA,NULL,
    (SELECT VALOR
    FROM SIM_CAT_TASA_REFER_DETALLE
    WHERE ID_TASA_REFERENCIA =
      (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
      )
    AND FECHA_PUBLICACION =
      (SELECT MAX(FECHA_PUBLICACION) FECHA_TASA_REFERENCIA
      FROM
        (SELECT FECHA_PUBLICACION
        FROM SIM_CAT_TASA_REFER_DETALLE
        WHERE ID_TASA_REFERENCIA =
          (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
          )
        AND FECHA_PUBLICACION < SYSDATE
        )
      )
    ),P.VALOR_TASA) VALOR_TASA,
    N.ID_SUCURSAL,
    S.NOM_SUCURSAL,
    S.TASA_IVA,
    D.CALLE
    ||' '
    ||D.NUMERO_INT
    ||' '
    ||D.NOM_ASENTAMIENTO
    ||' '
    ||D.NOM_DELEGACION
    ||' '
    ||D.NOM_ESTADO
    ||' '
    ||'C.P.'
    ||' '
    ||D.CODIGO_POSTAL DIRECCION_SUCURSAL,
    S.CVE_USUARIO_COORDINADOR,
    PCS.NOM_COMPLETO NOM_COORDINADOR_SUCURSAL,
    S.ID_REGIONAL,
    R.NOM_REGIONAL,
    P.FECHA_ENTREGA,
    P.FECHA_REAL,
    C.FECHA_FIN,
    P.CVE_ASESOR_CREDITO,
    PAA.NOM_COMPLETO NOM_ASESOR_CREDITO,
    P.CVE_ASESOR_FUNDADOR,
    PAF.NOM_COMPLETO NOM_ASESOR_FUNDADOR,
    P.ID_ETAPA_PRESTAMO,
    P.MONTO_FIJO_PERIODO,
    A.MONTO_AUTORIZADO,
    B.CARGO_INICIAL,
    P.NUM_LINEA,
    L.CVE_FONDEADOR,
    F.NOM_FONDEADOR
  FROM SIM_PRESTAMO_GRUPO P,
    SIM_GRUPO N,
    Sim_Producto O,
    SIM_CAT_METODO ME,
    (SELECT CVE_GPO_EMPRESA,
      CVE_EMPRESA,
      ID_PRESTAMO_GRUPO,
      SUM(MONTO_AUTORIZADO) MONTO_AUTORIZADO
    FROM SIM_PRESTAMO_GPO_DET
    GROUP BY ID_PRESTAMO_GRUPO,
      CVE_GPO_EMPRESA,
      CVE_EMPRESA
    ) A,
    (SELECT P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO_GRUPO,
      SUM(C.CARGO_INICIAL) CARGO_INICIAL
    FROM SIM_PRESTAMO_GPO_DET P,
      SIM_PRESTAMO_GPO_CARGO C
    WHERE C.CVE_GPO_EMPRESA   = P.CVE_GPO_EMPRESA
    AND C.CVE_EMPRESA         = P.CVE_EMPRESA
    AND C.ID_PRESTAMO_GRUPO   = P.ID_PRESTAMO_GRUPO
    AND C.ID_FORMA_APLICACION = 1
    GROUP BY P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO_GRUPO
    )B,
    (SELECT P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO_GRUPO,
      MAX(T.FECHA_AMORTIZACION) FECHA_FIN
    FROM SIM_PRESTAMO_GRUPO P,
      SIM_PRESTAMO_GPO_DET GD,
      SIM_TABLA_AMORTIZACION T
    WHERE GD.CVE_GPO_EMPRESA = P.CVE_GPO_EMPRESA
    AND GD.CVE_EMPRESA       = P.CVE_EMPRESA
    AND GD.ID_PRESTAMO_GRUPO = P.ID_PRESTAMO_GRUPO
    AND T.CVE_GPO_EMPRESA    = GD.CVE_GPO_EMPRESA
    AND T.CVE_EMPRESA        = GD.CVE_EMPRESA
    AND T.ID_PRESTAMO        = GD.ID_PRESTAMO
    GROUP BY P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO_GRUPO
    )C,
    SIM_CAT_SUCURSAL S,
    RS_GRAL_DOMICILIO D,
    SIM_CAT_PERIODICIDAD PE,
    SIM_CAT_PERIODICIDAD PET,
    RS_GRAL_USUARIO UAF,
    RS_GRAL_PERSONA PAF,
    RS_GRAL_USUARIO UAA,
    RS_GRAL_PERSONA PAA,
    SIM_CAT_REGIONAL R,
    RS_GRAL_USUARIO UCS,
    RS_GRAL_PERSONA PCS,
    SIM_CAT_FONDEADOR_LINEA L,
    SIM_CAT_FONDEADOR F
  WHERE N.CVE_GPO_EMPRESA     = P.CVE_GPO_EMPRESA
  AND N.CVE_EMPRESA           = P.CVE_EMPRESA
  AND N.ID_GRUPO              = P.ID_GRUPO
  AND A.CVE_GPO_EMPRESA       = P.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA           = P.CVE_EMPRESA
  AND A.ID_PRESTAMO_GRUPO     = P.ID_PRESTAMO_GRUPO
  AND B.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND B.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND B.ID_PRESTAMO_GRUPO (+) = P.ID_PRESTAMO_GRUPO
  AND C.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND C.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND C.ID_PRESTAMO_GRUPO (+) = P.ID_PRESTAMO_GRUPO
  AND O.CVE_GPO_EMPRESA       = P.CVE_GPO_EMPRESA
  AND O.CVE_EMPRESA           = P.CVE_EMPRESA
  AND O.Id_Producto           = P.Id_Producto
  AND Me.Cve_Gpo_Empresa      = P.Cve_Gpo_Empresa
  AND Me.Cve_Empresa          = P.Cve_Empresa
  AND ME.CVE_METODO           = P.CVE_METODO
  AND S.CVE_GPO_EMPRESA       = N.CVE_GPO_EMPRESA
  AND S.CVE_EMPRESA           = N.CVE_EMPRESA
  AND S.ID_SUCURSAL           = N.ID_SUCURSAL
  AND D.CVE_GPO_EMPRESA (+)   = S.CVE_GPO_EMPRESA
  AND D.CVE_EMPRESA (+)       = S.CVE_EMPRESA
  AND D.ID_DOMICILIO (+)      = S.ID_DIRECCION
  AND PE.CVE_GPO_EMPRESA      = P.CVE_GPO_EMPRESA
  AND PE.CVE_EMPRESA          = P.CVE_EMPRESA
  AND PE.ID_PERIODICIDAD      = P.ID_PERIODICIDAD_PRODUCTO
  AND PET.CVE_GPO_EMPRESA     = P.CVE_GPO_EMPRESA
  AND PET.CVE_EMPRESA         = P.CVE_EMPRESA
  AND PET.ID_PERIODICIDAD     = P.ID_PERIODICIDAD_TASA
  AND UAF.CVE_GPO_EMPRESA (+) = P.CVE_GPO_EMPRESA
  AND UAF.CVE_EMPRESA (+)     = P.CVE_EMPRESA
  AND UAF.CVE_USUARIO (+)     = P.CVE_ASESOR_FUNDADOR
  AND PAF.CVE_GPO_EMPRESA (+) = UAF.CVE_GPO_EMPRESA
  AND PAF.CVE_EMPRESA (+)     = UAF.CVE_EMPRESA
  AND PAF.ID_PERSONA (+)      = UAF.ID_PERSONA
  AND UAA.CVE_GPO_EMPRESA (+) = P.CVE_GPO_EMPRESA
  AND UAA.CVE_EMPRESA (+)     = P.CVE_EMPRESA
  AND UAA.CVE_USUARIO (+)     = P.CVE_ASESOR_FUNDADOR
  AND PAA.CVE_GPO_EMPRESA (+) = UAA.CVE_GPO_EMPRESA
  AND PAA.CVE_EMPRESA (+)     = UAA.CVE_EMPRESA
  AND PAA.ID_PERSONA (+)      = UAA.ID_PERSONA
  AND R.CVE_GPO_EMPRESA (+)   = S.CVE_GPO_EMPRESA
  AND R.CVE_EMPRESA (+)       = S.CVE_EMPRESA
  AND R.ID_REGIONAL (+)       = S.ID_REGIONAL
  AND UCS.CVE_GPO_EMPRESA (+) = S.CVE_GPO_EMPRESA
  AND UCS.CVE_EMPRESA (+)     = S.CVE_EMPRESA
  AND UCS.CVE_USUARIO (+)     = S.CVE_USUARIO_COORDINADOR
  AND PCS.CVE_GPO_EMPRESA (+) = UCS.CVE_GPO_EMPRESA
  AND PCS.CVE_EMPRESA (+)     = UCS.CVE_EMPRESA
  AND PCS.ID_PERSONA (+)      = UCS.ID_PERSONA
  AND L.CVE_GPO_EMPRESA (+)   = P.CVE_GPO_EMPRESA
  AND L.CVE_EMPRESA (+)       = P.CVE_EMPRESA
  AND L.NUM_LINEA (+)         = P.NUM_LINEA
  AND F.CVE_GPO_EMPRESA (+)   = L.CVE_GPO_EMPRESA
  AND F.CVE_EMPRESA (+)       = L.CVE_EMPRESA
  AND F.CVE_FONDEADOR (+)     = L.CVE_FONDEADOR
  UNION
  SELECT P.CVE_GPO_EMPRESA,
    P.CVE_EMPRESA,
    P.ID_PRESTAMO ID_PRESTAMO,
    P.CVE_PRESTAMO,
    'INDIVIDUAL_GRUPO' APLICA_A,
    P.ID_CLIENTE CVE_NOMBRE,
    N.NOM_COMPLETO NOMBRE,
    P.ID_PRODUCTO,
    O.NOM_PRODUCTO,
    P.NUM_CICLO,
    P.ID_PERIODICIDAD_PRODUCTO,
    PE.NOM_PERIODICIDAD PERIODICIDAD_PRODUCTO,
    P.Plazo,
    P.DIA_SEMANA_PAGO,
    P.Cve_Metodo,
    ME.NOM_METODO,
    DECODE(P.ID_PERIODICIDAD_TASA,NULL,
    (SELECT ID_PERIODICIDAD
    FROM SIM_CAT_TASA_REFERENCIA
    WHERE ID_TASA_REFERENCIA =
      (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
      )
    ),P.ID_PERIODICIDAD_TASA) ID_PERIODICIDAD_TASA,
    PET.NOM_PERIODICIDAD PERIODICIDAD_TASA,
    DECODE(P.VALOR_TASA,NULL,
    (SELECT VALOR
    FROM SIM_CAT_TASA_REFER_DETALLE
    WHERE ID_TASA_REFERENCIA =
      (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
      )
    AND FECHA_PUBLICACION =
      (SELECT MAX(FECHA_PUBLICACION) FECHA_TASA_REFERENCIA
      FROM
        (SELECT FECHA_PUBLICACION
        FROM SIM_CAT_TASA_REFER_DETALLE
        WHERE ID_TASA_REFERENCIA =
          (SELECT ID_TASA_REFERENCIA FROM SIM_PRESTAMO_GRUPO
          )
        AND FECHA_PUBLICACION < SYSDATE
        )
      )
    ),P.VALOR_TASA) VALOR_TASA,
    P.ID_SUCURSAL,
    S.NOM_SUCURSAL,
    S.TASA_IVA,
    D.CALLE
    ||' '
    ||D.NUMERO_INT
    ||' '
    ||D.NOM_ASENTAMIENTO
    ||' '
    ||D.NOM_DELEGACION
    ||' '
    ||D.NOM_ESTADO
    ||' '
    ||'C.P.'
    ||' '
    ||D.CODIGO_POSTAL DIRECCION_SUCURSAL,
    S.CVE_USUARIO_COORDINADOR,
    PCS.NOM_COMPLETO NOM_COORDINADOR_SUCURSAL,
    S.ID_REGIONAL,
    R.NOM_REGIONAL,
    P.FECHA_ENTREGA,
    P.FECHA_REAL,
    T.FECHA_FIN,
    P.CVE_ASESOR_CREDITO,
    PAA.NOM_COMPLETO NOM_ASESOR_CREDITO,
    P.CVE_ASESOR_FUNDADOR,
    PAF.NOM_COMPLETO NOM_ASESOR_FUNDADOR,
    P.ID_ETAPA_PRESTAMO,
    P.MONTO_FIJO_PERIODO,
    M.MONTO_AUTORIZADO,
    NVL(C.CARGO_INICIAL,C.PORCENTAJE_MONTO/100*M.MONTO_AUTORIZADO) CARGO_INICIAL,
    P.NUM_LINEA,
    L.CVE_FONDEADOR,
    F.NOM_FONDEADOR
  FROM SIM_PRESTAMO P,
    RS_GRAL_PERSONA N,
    SIM_CLIENTE_MONTO M,
    SIM_PRESTAMO_CARGO_COMISION C,
    Sim_Producto O,
    SIM_CAT_METODO ME,
    SIM_CAT_SUCURSAL S,
    RS_GRAL_DOMICILIO D,
    SIM_CAT_PERIODICIDAD PE,
    SIM_CAT_PERIODICIDAD PET,
    (SELECT P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO,
      MAX(T.FECHA_AMORTIZACION) FECHA_FIN
    FROM SIM_PRESTAMO P,
      SIM_TABLA_AMORTIZACION T
    WHERE T.CVE_GPO_EMPRESA = P.CVE_GPO_EMPRESA
    AND T.CVE_EMPRESA       = P.CVE_EMPRESA
    AND T.ID_PRESTAMO       = P.ID_PRESTAMO
    GROUP BY P.CVE_GPO_EMPRESA,
      P.CVE_EMPRESA,
      P.ID_PRESTAMO
    )T,
    RS_GRAL_USUARIO UAF,
    RS_GRAL_PERSONA PAF,
    RS_GRAL_USUARIO UAA,
    RS_GRAL_PERSONA PAA,
    SIM_CAT_REGIONAL R,
    RS_GRAL_USUARIO UCS,
    RS_GRAL_PERSONA PCS,
    SIM_CAT_FONDEADOR_LINEA L,
    SIM_CAT_FONDEADOR F
  WHERE P.ID_PRESTAMO IN
    (SELECT ID_PRESTAMO FROM SIM_PRESTAMO_GPO_DET
    )
  AND N.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND N.CVE_EMPRESA            = P.CVE_EMPRESA
  AND N.ID_PERSONA             = P.ID_CLIENTE
  AND M.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND M.CVE_EMPRESA            = P.CVE_EMPRESA
  AND M.ID_PRESTAMO            = P.ID_PRESTAMO
  AND C.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND C.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND C.ID_PRESTAMO (+)        = P.ID_PRESTAMO
  AND C.ID_FORMA_APLICACION (+)= 1
  AND C.ID_CARGO_COMISION (+)  = 9
  AND O.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND O.CVE_EMPRESA            = P.CVE_EMPRESA
  AND O.ID_PRODUCTO            = P.ID_PRODUCTO
  AND Me.Cve_Gpo_Empresa       = P.Cve_Gpo_Empresa
  AND Me.Cve_Empresa           = P.Cve_Empresa
  AND ME.CVE_METODO            = P.CVE_METODO
  AND S.CVE_GPO_EMPRESA        = P.CVE_GPO_EMPRESA
  AND S.CVE_EMPRESA            = P.CVE_EMPRESA
  AND S.ID_SUCURSAL            = P.ID_SUCURSAL
  AND D.CVE_GPO_EMPRESA (+)    = S.CVE_GPO_EMPRESA
  AND D.CVE_EMPRESA (+)        = S.CVE_EMPRESA
  AND D.ID_DOMICILIO (+)       = S.ID_DIRECCION
  AND PE.CVE_GPO_EMPRESA       = P.CVE_GPO_EMPRESA
  AND PE.CVE_EMPRESA           = P.CVE_EMPRESA
  AND PE.ID_PERIODICIDAD       = P.ID_PERIODICIDAD_PRODUCTO
  AND PET.CVE_GPO_EMPRESA      = P.CVE_GPO_EMPRESA
  AND PET.CVE_EMPRESA          = P.CVE_EMPRESA
  AND PET.ID_PERIODICIDAD      = P.ID_PERIODICIDAD_TASA
  AND T.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND T.Cve_Empresa (+)        = P.Cve_Empresa
  AND T.ID_PRESTAMO (+)        = P.ID_PRESTAMO
  AND UAF.CVE_GPO_EMPRESA (+)  = P.CVE_GPO_EMPRESA
  AND UAF.CVE_EMPRESA (+)      = P.CVE_EMPRESA
  AND UAF.CVE_USUARIO (+)      = P.CVE_ASESOR_FUNDADOR
  AND PAF.CVE_GPO_EMPRESA (+)  = UAF.CVE_GPO_EMPRESA
  AND PAF.CVE_EMPRESA (+)      = UAF.CVE_EMPRESA
  AND PAF.ID_PERSONA (+)       = UAF.ID_PERSONA
  AND UAA.CVE_GPO_EMPRESA (+)  = P.CVE_GPO_EMPRESA
  AND UAA.CVE_EMPRESA (+)      = P.CVE_EMPRESA
  AND UAA.CVE_USUARIO (+)      = P.CVE_ASESOR_FUNDADOR
  AND PAA.CVE_GPO_EMPRESA (+)  = UAA.CVE_GPO_EMPRESA
  AND PAA.CVE_EMPRESA (+)      = UAA.CVE_EMPRESA
  AND PAA.ID_PERSONA (+)       = UAA.ID_PERSONA
  AND R.CVE_GPO_EMPRESA (+)    = S.CVE_GPO_EMPRESA
  AND R.CVE_EMPRESA (+)        = S.CVE_EMPRESA
  AND R.ID_REGIONAL (+)        = S.ID_REGIONAL
  AND UCS.CVE_GPO_EMPRESA (+)  = S.CVE_GPO_EMPRESA
  AND UCS.CVE_EMPRESA (+)      = S.CVE_EMPRESA
  AND UCS.CVE_USUARIO (+)      = S.CVE_USUARIO_COORDINADOR
  AND PCS.CVE_GPO_EMPRESA (+)  = UCS.CVE_GPO_EMPRESA
  AND PCS.CVE_EMPRESA (+)      = UCS.CVE_EMPRESA
  AND PCS.ID_PERSONA (+)       = UCS.ID_PERSONA
  AND L.CVE_GPO_EMPRESA (+)    = P.CVE_GPO_EMPRESA
  AND L.CVE_EMPRESA (+)        = P.CVE_EMPRESA
  AND L.NUM_LINEA (+)          = P.NUM_LINEA
  AND F.CVE_GPO_EMPRESA (+)    = L.CVE_GPO_EMPRESA
  AND F.CVE_EMPRESA (+)        = L.CVE_EMPRESA
  AND F.CVE_FONDEADOR (+)      = L.CVE_FONDEADOR;
 
