
  CREATE OR REPLACE FORCE VIEW "V_SIM_PRESTAMO_GPO_MOV_EDO_CTA" ("CVE_GPO_EMPRESA", "CVE_EMPRESA", "ID_PRESTAMO", "F_OPERACION", "NUM_PAGO_AMORTIZACION", "F_APLICACION", "DESC_MOVIMIENTO", "IMP_PAGO", "IMP_CONCEPTO", "ID_MOVIMIENTO") AS 
  SELECT G.CVE_GPO_EMPRESA,
    G.CVE_EMPRESA,
    G.ID_PRESTAMO_GRUPO  AS ID_PRESTAMO,
    A.FECHA_AMORTIZACION AS F_OPERACION,
    A.NUM_PAGO_AMORTIZACION,
    A.FECHA_AMORTIZACION AS F_APLICACION,
    INITCAP(B.DESC_CORTA),
    0                   AS IMP_PAGO,
    SUM(A.IMP_ORIGINAL) AS IMP_CONCEPTO,
    0                   AS ID_MOVIMIENTO
  FROM SIM_PRESTAMO_GPO_DET G,
    V_SIM_TABLA_AMORT_CONCEPTO A,
    PFIN_CAT_CONCEPTO B
  WHERE G.CVE_GPO_EMPRESA = A.CVE_GPO_EMPRESA
  AND G.CVE_EMPRESA       = A.CVE_EMPRESA
  AND G.ID_PRESTAMO       = A.ID_PRESTAMO
  AND A.CVE_GPO_EMPRESA   = B.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA       = B.CVE_EMPRESA
  AND A.CVE_CONCEPTO      = B.CVE_CONCEPTO
  AND A.IMP_ORIGINAL     <> 0
  GROUP BY G.CVE_GPO_EMPRESA,
    G.CVE_EMPRESA,
    G.ID_PRESTAMO_GRUPO,
    A.FECHA_AMORTIZACION,
    A.NUM_PAGO_AMORTIZACION,
    A.FECHA_AMORTIZACION,
    B.CVE_CONCEPTO,
    INITCAP(B.DESC_CORTA)
  UNION ALL
  SELECT G.CVE_GPO_EMPRESA,
    G.CVE_EMPRESA,
    G.ID_PRESTAMO_GRUPO AS ID_PRESTAMO,
    A.F_OPERACION,
    A.NUM_PAGO_AMORTIZACION,
    A.F_APLICACION,
    'Pago '
    || INITCAP(C.DESC_CORTA),
    0                   AS IMP_PAGO,
    SUM(B.IMP_CONCEPTO) AS IMP_CONCEPTO,
    A.ID_MOVIMIENTO
  FROM SIM_PRESTAMO_GPO_DET G,
    PFIN_MOVIMIENTO A,
    PFIN_MOVIMIENTO_DET B,
    PFIN_CAT_CONCEPTO C
  WHERE G.CVE_GPO_EMPRESA = A.CVE_GPO_EMPRESA
  AND G.CVE_EMPRESA       = A.CVE_EMPRESA
  AND G.ID_PRESTAMO       = A.ID_PRESTAMO
  AND A.CVE_GPO_EMPRESA   = B.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA       = B.CVE_EMPRESA
  AND A.ID_MOVIMIENTO     = B.ID_MOVIMIENTO
  AND A.SIT_MOVIMIENTO   <> 'CA'
  AND B.CVE_GPO_EMPRESA   = C.CVE_GPO_EMPRESA
  AND B.CVE_EMPRESA       = C.CVE_EMPRESA
  AND B.CVE_CONCEPTO      = C.CVE_CONCEPTO
  GROUP BY G.CVE_GPO_EMPRESA,
    G.CVE_EMPRESA,
    G.ID_PRESTAMO_GRUPO,
    A.F_OPERACION,
    A.NUM_PAGO_AMORTIZACION,
    A.F_APLICACION,
    INITCAP(C.DESC_CORTA),
    A.ID_MOVIMIENTO,
    B.CVE_CONCEPTO
  UNION ALL
  SELECT G.CVE_GPO_EMPRESA,
    G.CVE_EMPRESA,
    G.ID_PRESTAMO_GRUPO AS ID_PRESTAMO,
    A.F_OPERACION,
    A.NUM_PAGO_AMORTIZACION,
    A.F_APLICACION,
    'Pago prestamo',
    A.IMP_NETO AS IMP_PAGO,
    0          AS IMP_CONCEPTO,
    A.ID_MOVIMIENTO
  FROM SIM_PRESTAMO_GPO_DET G,
    PFIN_MOVIMIENTO A
  WHERE G.CVE_GPO_EMPRESA = A.CVE_GPO_EMPRESA
  AND G.CVE_EMPRESA       = A.CVE_EMPRESA
  AND G.ID_PRESTAMO       = A.ID_PRESTAMO
  AND A.SIT_MOVIMIENTO   <> 'CA';
 
