
  CREATE OR REPLACE FORCE VIEW "V_SIM_PRESTAMO_GPO_RES_EDO_CTA" ("CVE_GPO_EMPRESA", "CVE_EMPRESA", "ID_PRESTAMO", "DESC_MOVIMIENTO", "IMP_DEBE_TOTAL", "IMP_PAGO_TOTAL", "IMP_SALDO_TOTAL", "IMP_DEBE_HOY", "IMP_PAGO_HOY", "IMP_SALDO_HOY") AS 
  SELECT A.CVE_GPO_EMPRESA,
    A.CVE_EMPRESA,
    A.ID_PRESTAMO,
    A.DESC_MOVIMIENTO,
    SUM(IMP_CONCEPTO * -1)                 AS IMP_DEBE_TOTAL,
    SUM(IMP_PAGO)                          AS IMP_PAGO_TOTAL,
    SUM(IMP_CONCEPTO * -1) - SUM(IMP_PAGO) AS IMP_SALDO_TOTAL,
    SUM(
    CASE
      WHEN A.F_APLICACION > B.F_MEDIO
      THEN 0
      ELSE IMP_CONCEPTO * -1
    END) AS IMP_DEBE_HOY,
    SUM(
    CASE
      WHEN A.F_APLICACION > B.F_MEDIO
      THEN 0
      ELSE IMP_PAGO
    END) AS IMP_PAGO_HOY,
    SUM(
    CASE
      WHEN A.F_APLICACION > B.F_MEDIO
      THEN 0
      ELSE IMP_CONCEPTO * -1
    END)                - SUM(
    CASE
      WHEN A.F_APLICACION > B.F_MEDIO
      THEN 0
      ELSE IMP_PAGO
    END) AS IMP_SALDO_HOY
  FROM V_SIM_PRESTAMO_GPO_MOV_EDO_CTA A,
    PFIN_PARAMETRO B
  WHERE A.CVE_GPO_EMPRESA = B.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA       = B.CVE_EMPRESA
  AND 'SYSTEM'            = B.CVE_MEDIO
  GROUP BY A.CVE_GPO_EMPRESA,
    A.CVE_EMPRESA,
    A.ID_PRESTAMO,
    A.DESC_MOVIMIENTO
  ORDER BY A.DESC_MOVIMIENTO;
 
