
  CREATE OR REPLACE FORCE VIEW "V_TABLA_AMORTIZACION_GRUPAL" ("CVE_GPO_EMPRESA", "CVE_EMPRESA", "ID_PRESTAMO_GRUPO", "CVE_PRESTAMO_GRUPO", "NUM_PAGO_AMORTIZACION", "FECHA_AMORTIZACION", "IMP_SALDO_INICIAL", "TASA_INTERES", "INTERES", "IMP_CAPITAL_AMORT", "IMP_PAGO", "IMP_ACCESORIO", "PAGO_TOTAL", "IMP_SALDO_FINAL", "B_PAGADO") AS 
  SELECT B.CVE_GPO_EMPRESA,
    B.CVE_EMPRESA,
    B.ID_PRESTAMO_GRUPO,
    B.CVE_PRESTAMO_GRUPO,
    B.NUM_PAGO_AMORTIZACION,
    B.FECHA_AMORTIZACION,
    TO_CHAR(B.IMP_SALDO_INICIAL,'999,999,999.9999') IMP_SALDO_INICIAL,
    B.TASA_INTERES,
    B.INTERES,
    B.IMP_CAPITAL_AMORT,
    B.IMP_PAGO,
    A.IMP_ACCESORIO,
    B.IMP_PAGO + A.IMP_ACCESORIO PAGO_TOTAL,
    TO_CHAR(B.IMP_SALDO_FINAL,'999,999,999.9999') IMP_SALDO_FINAL,
    B.B_PAGADO
  FROM
    (SELECT T.CVE_GPO_EMPRESA,
      T.CVE_EMPRESA,
      GT.ID_PRESTAMO_GRUPO,
      PG.CVE_PRESTAMO_GRUPO,
      T.NUM_PAGO_AMORTIZACION,
      T.FECHA_AMORTIZACION,
      SUM(A.IMP_ACCESORIO) IMP_ACCESORIO
    FROM SIM_PRESTAMO_GPO_DET GT,
      SIM_TABLA_AMORTIZACION T,
      SIM_TABLA_AMORT_ACCESORIO A,
      SIM_CAT_ACCESORIO N,
      SIM_PRESTAMO_GRUPO PG,
      SIM_GRUPO G,
      SIM_PRODUCTO P
    WHERE GT.CVE_GPO_EMPRESA    = 'SIM'
    AND GT.CVE_EMPRESA          = 'CREDICONFIA'
    AND T.CVE_GPO_EMPRESA       = GT.CVE_GPO_EMPRESA
    AND T.CVE_EMPRESA           = GT.CVE_EMPRESA
    AND T.ID_PRESTAMO           = GT.ID_PRESTAMO
    AND A.CVE_GPO_EMPRESA       = T.CVE_GPO_EMPRESA
    AND A.CVE_EMPRESA           = T.CVE_EMPRESA
    AND A.ID_PRESTAMO           = T.ID_PRESTAMO
    AND A.NUM_PAGO_AMORTIZACION = T.NUM_PAGO_AMORTIZACION
    AND N.CVE_GPO_EMPRESA       = A.CVE_GPO_EMPRESA
    AND N.CVE_EMPRESA           = A.CVE_EMPRESA
    AND N.ID_ACCESORIO          = A.ID_ACCESORIO
    AND PG.CVE_GPO_EMPRESA      = GT.CVE_GPO_EMPRESA
    AND PG.CVE_EMPRESA          = GT.CVE_EMPRESA
    AND PG.ID_PRESTAMO_GRUPO    = GT.ID_PRESTAMO_GRUPO
    AND G.CVE_GPO_EMPRESA       = PG.CVE_GPO_EMPRESA
    AND G.CVE_EMPRESA           = PG.CVE_EMPRESA
    AND G.ID_GRUPO              = PG.ID_GRUPO
    AND P.CVE_GPO_EMPRESA       = PG.CVE_GPO_EMPRESA
    AND P.CVE_EMPRESA           = PG.CVE_EMPRESA
    AND P.ID_PRODUCTO           = PG.ID_PRODUCTO
    GROUP BY T.CVE_GPO_EMPRESA,
      T.CVE_EMPRESA,
      GT.ID_PRESTAMO_GRUPO,
      PG.CVE_PRESTAMO_GRUPO,
      T.NUM_PAGO_AMORTIZACION,
      T.FECHA_AMORTIZACION,
      T.TASA_INTERES
    ORDER BY PG.CVE_PRESTAMO_GRUPO,
      T.NUM_PAGO_AMORTIZACION
    )A,
    (SELECT T.CVE_GPO_EMPRESA,
      T.CVE_EMPRESA,
      GT.ID_PRESTAMO_GRUPO,
      PG.CVE_PRESTAMO_GRUPO,
      G.NOM_GRUPO,
      P.NOM_PRODUCTO,
      PG.NUM_CICLO,
      T.NUM_PAGO_AMORTIZACION,
      T.FECHA_AMORTIZACION,
      SUM(T.IMP_SALDO_INICIAL) IMP_SALDO_INICIAL,
      T.TASA_INTERES,
      SUM(NVL(T.IMP_INTERES,0) + NVL(T.IMP_INTERES_EXTRA,0) + NVL(T.IMP_IVA_INTERES,0) + NVL(T.IMP_IVA_INTERES_EXTRA,0)) INTERES,
      SUM(T.IMP_CAPITAL_AMORT) IMP_CAPITAL_AMORT,
      SUM(T.IMP_PAGO) IMP_PAGO,
      SUM(T.IMP_SALDO_FINAL) IMP_SALDO_FINAL,
      T.B_PAGADO
    FROM SIM_PRESTAMO_GPO_DET GT,
      SIM_TABLA_AMORTIZACION T,
      SIM_PRESTAMO_GRUPO PG,
      SIM_GRUPO G,
      SIM_PRODUCTO P
    WHERE GT.CVE_GPO_EMPRESA = 'SIM'
    AND GT.CVE_EMPRESA       = 'CREDICONFIA'
    AND T.CVE_GPO_EMPRESA    = GT.CVE_GPO_EMPRESA
    AND T.CVE_EMPRESA        = GT.CVE_EMPRESA
    AND T.ID_PRESTAMO        = GT.ID_PRESTAMO
    AND PG.CVE_GPO_EMPRESA   = GT.CVE_GPO_EMPRESA
    AND PG.CVE_EMPRESA       = GT.CVE_EMPRESA
    AND PG.ID_PRESTAMO_GRUPO = GT.ID_PRESTAMO_GRUPO
    AND G.CVE_GPO_EMPRESA    = PG.CVE_GPO_EMPRESA
    AND G.CVE_EMPRESA        = PG.CVE_EMPRESA
    AND G.ID_GRUPO           = PG.ID_GRUPO
    AND P.CVE_GPO_EMPRESA    = PG.CVE_GPO_EMPRESA
    AND P.CVE_EMPRESA        = PG.CVE_EMPRESA
    AND P.ID_PRODUCTO        = PG.ID_PRODUCTO
    GROUP BY T.CVE_GPO_EMPRESA,
      T.CVE_EMPRESA,
      GT.ID_PRESTAMO_GRUPO,
      PG.CVE_PRESTAMO_GRUPO,
      G.NOM_GRUPO,
      P.NOM_PRODUCTO,
      PG.NUM_CICLO,
      T.NUM_PAGO_AMORTIZACION,
      T.FECHA_AMORTIZACION,
      T.TASA_INTERES,
      T.B_PAGADO
    ORDER BY GT.ID_PRESTAMO_GRUPO,
      T.NUM_PAGO_AMORTIZACION
    )B
  WHERE A.CVE_GPO_EMPRESA     = B.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA           = B.CVE_EMPRESA
  AND A.ID_PRESTAMO_GRUPO     = B.ID_PRESTAMO_GRUPO
  AND A.NUM_PAGO_AMORTIZACION = B.NUM_PAGO_AMORTIZACION
  GROUP BY B.CVE_GPO_EMPRESA,
    B.CVE_EMPRESA,
    B.ID_PRESTAMO_GRUPO,
    B.CVE_PRESTAMO_GRUPO,
    B.NUM_PAGO_AMORTIZACION,
    B.FECHA_AMORTIZACION,
    TO_CHAR(B.IMP_SALDO_INICIAL,'999,999,999.9999'),
    B.TASA_INTERES,
    B.INTERES,
    B.IMP_CAPITAL_AMORT,
    B.IMP_PAGO,
    A.IMP_ACCESORIO,
    TO_CHAR(B.IMP_PAGO + A.IMP_ACCESORIO,'999,999,999.9999'),
    TO_CHAR(B.IMP_SALDO_FINAL,'999,999,999.9999'),
    B.IMP_SALDO_INICIAL,
    B.INTERES,
    B.IMP_CAPITAL_AMORT,
    B.IMP_PAGO,
    A.IMP_ACCESORIO,
    B.IMP_SALDO_FINAL,
    B.B_PAGADO
  ORDER BY Id_Prestamo_Grupo,
    NUM_PAGO_AMORTIZACION;
 
